version: '3.9'
services:
  web:
    build: ./
    restart: always
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./bsl/:/usr/src/app/
    ports:
      - 9000:9000
    env_file:
      - ./bsl/.env_docker
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'bsl'
      MYSQL_USER: 'bsl'
      MYSQL_PASSWORD: 'Qwerty123'
      MYSQL_ROOT_PASSWORD: 'Qwerty123'
    restart: always
    volumes:
      - ./bsl/db:/var/lib/mysql
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - web