# Generated by Django 3.1.5 on 2021-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
                ('hold', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
