# Generated by Django 3.1.5 on 2021-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside_bsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonents',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
