# Generated by Django 3.1.5 on 2021-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside_bsl', '0002_auto_20210806_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonents',
            name='status',
            field=models.BooleanField(),
        ),
    ]
